version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - appdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    networks:
      - db-network
volumes:
  appdata: null

networks:
  db-network:
    driver: bridge
