name: ✨

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Linter
        run: yarn && yarn format:check
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Test
        run: |
          yarn && yarn test
          echo "// TODO: Fix test CI/CD"
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
